### ISSUE TITLE
How to change server URL

### ISSUE THREAD

**Issue by mworsnop** [mauro-midolo/homeassistant_webserver_status#8]
Sorry for the silly question, How do I change server URL. This has been working really well, but my server has changed and I need to change the URL. Do I delete it and re-add it or something?

**Comment by mauro-midolo** [comment]
Ciao @mworsnop,
It is not currently possible to change URLs of an existing entry.
The only way is to delete and create a new value.

**Comment by mworsnop** [comment]
thank you! take care
